### ISSUE TITLE
Missing features in GitLab implementation

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#158]
Since we merged [the PR with the basic GitLab support](https://github.com/packit-service/ogr/pull/150) is there still something missing?

- [x] service mapping (#156 )
- [x] fix the mix of new and old API (#167 )
- [x] missing methods:
    - [x] forking: https://github.com/packit-service/ogr/issues/168
    - [x] owners and permissions: https://github.com/packit-service/ogr/issues/169
    - [x] get_sha_from_tag: https://github.com/packit-service/ogr/issues/170
    - [x] issue labels: https://github.com/packit-service/ogr/issues/171
    - [x] commit comment/status: https://github.com/packit-service/ogr/issues/172
    - [x] pr close/merge: https://github.com/packit-service/ogr/issues/173
    - [x] PR labels: https://github.com/packit-service/ogr/issues/174
    - [x] project info: https://github.com/packit-service/ogr/issues/175
    - [x] latest release: https://github.com/packit-service/ogr/issues/176

**Comment by lachmanfrantisek** [comment]
I am currently fixing some naming issues after the merge of the first version. (We have mixed the old and new API a bit.) After that, I'll update this issue and we will have a couple of good-first-issues..;)

**Comment by lachmanfrantisek** [comment]
Old code snippet for forking that I need+want to remove:

```python

    @staticmethod
    def is_fork_of(user_repo, target_repo):
        """ is provided repo fork of the {parent_repo}/? """
        return user_repo.forked_from_project["id"] == target_repo.id

    def fork(self, target_repo):
        target_repo_org, target_repo_name = target_repo.split("/", 1)

        target_repo_gl = self.gitlab_instance.projects.get(target_repo)

        try:
            # is it already forked?
            user_repo = self.gitlab_instance.projects.get(
                "{}/{}".format(self.user.get_username(), target_repo_name)
            )
            if not self.is_fork_of(user_repo, target_repo_gl):
                raise RuntimeError(
                    "repo %s is not a fork of %s" % (user_repo, target_repo_gl)
                )
        except Exception:
            # nope
            user_repo = None

        if self.user.get_username() == target_repo_org:
            # user wants to fork its own repo; let's just set up remotes 'n stuff
            if not user_repo:
                raise RuntimeError("repo %s not found" % target_repo_name)
            clone_repo_and_cd_inside(
                user_repo.path, user_repo.attributes["ssh_url_to_repo"], target_repo_org
            )
        else:
            user_repo = user_repo or self._fork_gracefully(target_repo_gl)

            clone_repo_and_cd_inside(
                user_repo.path, user_repo.attributes["ssh_url_to_repo"], target_repo_org
            )

            set_upstream_remote(
                clone_url=target_repo_gl.attributes["http_url_to_repo"],
                ssh_url=target_repo_gl.attributes["ssh_url_to_repo"],
                pull_merge_name="merge-requests",
            )
        set_origin_remote(
            user_repo.attributes["ssh_url_to_repo"], pull_merge_name="merge-requests"
        )
        fetch_all()

    @staticmethod
    def _fork_gracefully(target_repo):
        """ fork if not forked, return forked repo """
        try:
            logger.info("forking repo %s", target_repo)
            fork = target_repo.forks.create({})
        except gitlab.GitlabCreateError:
            logger.error("repo %s cannot be forked" % target_repo)
            raise RuntimeError("repo %s not found" % target_repo)

        return fork
```

**Comment by lachmanfrantisek** [comment]
@lbarcziova Nice job with all these pull-requests. We are finally done!
